// Register User
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// Delete User
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// Load User List
export const LOAD_USER_LIST_REQUEST = 'LOAD_USER_LIST_REQUEST';
export const LOAD_USER_LIST_SUCCESS = 'LOAD_USER_LIST_SUCCESS';
export const LOAD_USER_LIST_FAILURE = 'LOAD_USER_LIST_FAILURE';


// Generate Team
export const GENERATE_TEAM_REQUEST = 'GENERATE_TEAM_REQUEST';
export const GENERATE_TEAM_SUCCESS = 'GENERATE_TEAM_SUCCESS';
export const GENERATE_TEAM_FAILURE = 'GENERATE_TEAM_FAILURE';

// Generate Team
export const DETAIL_TEAM_REQUEST = 'DETAIL_TEAM_REQUEST';
export const DETAIL_TEAM_SUCCESS = 'DETAIL_TEAM_SUCCESS';
export const DETAIL_TEAM_FAILURE = 'DETAIL_TEAM_FAILURE';

